name: test and lint pullrequest changes

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: 1.24.3
    - name: Run test
      run: make test
    - name: Lint programs
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.4
        skip-cache: true
        skip-save-cache: true
        install-mode: binary
    - name: Modernize check
      run: make modernize
