name: Release with artifact

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: 1.24.3
      - name: Run test
        run: make test
      - name: Lint programs
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v2.4
          skip-cache: true
          skip-save-cache: true
          install-mode: binary
      - name: Modernize check
        run: make modernize
      - name: Set version
        id: version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Build platform binaries
        run: VERSION=${{ steps.version.outputs.version }} make all
      - name: Create Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/tfopen-linux-amd64
            dist/tfopen-linux-arm64
            dist/tfopen-darwin-amd64
            dist/tfopen-darwin-arm64
            dist/tfopen-linux-amd64.tar.gz
            dist/tfopen-linux-arm64.tar.gz
            dist/tfopen-darwin-amd64.tar.gz
            dist/tfopen-darwin-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
