name: Release with artifact

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: 1.24.3
      - name: Run tests
        run: |
          make test
          make lint
          make modernize
      - name: Lint programs
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6.5.2
        with:
          version: v2.4.0
          skip-cache: true
          skip-save-cache: true
          install-mode: binary
      - name: Set version
        id: version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Build platform binaries
        run: VERSION=${{ steps.version.outputs.version }} make all
      - name: Create Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/tfopen-linux-amd64
            dist/tfopen-linux-arm64
            dist/tfopen-darwin-amd64
            dist/tfopen-darwin-arm64
            dist/tfopen-linux-amd64.tar.gz
            dist/tfopen-linux-arm64.tar.gz
            dist/tfopen-darwin-amd64.tar.gz
            dist/tfopen-darwin-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
